In [ ]:
import numpy as np

#Creacion de ndarrays = arrays

#lista de numeros
numeros = [1, 2, 3, 4, 5]

#creacion de ndarrays a partir de lista de numeros
ndarrays_array = np.array(numeros)

print(ndarrays_array)
#salida [1 2 3 4 5]

[1 2 3 4 5]


In [ ]:
#creacion de un ndarrays de 2x3 con ceros
matriz_ceros = np.zeros((2,3))

#creacion de un ndarrays de 3x3 con uno
matriz_unos = np.ones((3,3))

#creacion de un ndarrays con numeros [2,3,5] y [4,7,9]
matriz_datos_especificos = np.array([[2, 3, 5],[4, 7, 9]])

print(matriz_ceros)
print(matriz_unos)
print(matriz_datos_especificos)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2 3 5]
 [4 7 9]]


In [ ]:
#creacion de un ndarray con valores 0, al 9 (sin incluir el 10)
numeros_0_a_9 = np.arange(0, 10)
print(numeros_0_a_9)

#creaion de un ndarray del 1 al 5 de 2 en 2
numeros_del_1_al_5 = np.arange(1, 6, 2)
print(numeros_del_1_al_5)

#creacion de un ndarray con valores del 0 al 4 (sin incuir el 4) de 0.5 en 0.5
numeros_0_al_4 = np.arange(0, 4, 0.5)
print(numeros_0_al_4)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5]


In [ ]:
#creacion de un ndarray con 10 valores espaciados uniformemente entre 0 y 1
numeros_espaciados = np.linspace (0, 1, 10)
print(numeros_espaciados)

#creacion de un ndarray con 5 valores espaciados uniformemente entre 2 y 10
numeros_entre_2_10 = np.linspace(2, 10, 5)
print(numeros_entre_2_10)

[0.         0.22222222 0.44444444 0.66666667 0.88888889 1.11111111
 1.33333333 1.55555556 1.77777778 2.        ]
[ 2.  4.  6.  8. 10.]


In [ ]:
#creacion de un ndarray de 3x3 con numeros aleteorios entre 0 y 1
matriz_aleatoria = np.random.rand(3, 3)
print(matriz_aleatoria)

#creacion de un ndarray de 5 elementos con numeros aleatorios entre 0 y 1
vector_aleatorio = np.random.rand(5)
print(vector_aleatorio)

[[0.19605471 0.50935154 0.39906135]
 [0.75927057 0.53955923 0.60984748]
 [0.00699289 0.80700401 0.54817258]]
[0.64839649 0.0882076  0.7492956  0.82798621 0.52976033]


In [ ]:
#creacion de un ndarray 2D
matriz = np.array([[1, 2, 3], [4, 5, 6]])

#acceso a un alemnto especifico (fila 1, culumna 2)
elemento = matriz[1, 2]
print(elemento)

#seleccion de una fila (fila 0)
fila = matriz[0, :]
print(fila)

#seleccion de una columna (columna 1)
columna = matriz[:, 1]
print(columna)

6
[1 2 3]
[2 5]


In [ ]:
arr = np.array([1, 2, 3])
print(np.sum(arr))

6


In [ ]:
from os import renames
array = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array.reshape(3, 2)
fattened_array = array.flatten()
transposed_array = array.T
print("Array Original")
print(array)
print("Array Reshape")
print(reshaped_array)
print("Array Flaten")
print(fattened_array)
print("Array Transposed")
print(transposed_array)


Array Original
[[1 2 3]
 [4 5 6]]
Array Reshape
[[1 2]
 [3 4]
 [5 6]]
Array Flaten
[1 2 3 4 5 6]
Array Transposed
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
numeros_aleatorios_uniforme = np.random.rand(5)
numeros_aleatorios_enteros = np.random.randint(1, 10, size=5)
numeros_aleatorios_normales = np.random.randn(2, 2)

print("Numeros aleatorios uniformes:")
print(numeros_aleatorios_uniforme)
print("Numeros aleatorios enteros:")
print(numeros_aleatorios_enteros)
print("Numeros aleatorios normales:")
print(numeros_aleatorios_normales)

Numeros aleatorios uniformes:
[0.27418788 0.92560506 0.31492077 0.53130795 0.05479075]
Numeros aleatorios enteros:
[1 4 8 5 7]
Numeros aleatorios normales:
[[0.55118636 0.46153518]
 [0.42491165 0.38060554]]


In [ ]:
sumar1 = np.array([1, 2, 3])
sumar2 = np.array([4, 5, 6])
suma = sumar1 + sumar2
print(suma)


[5 7 9]


In [ ]:
multipliacion1 = np.array([1, 2, 3])
multiplicacion2 = np.array([4, 5, 6])
multi = 2 * multiplicacion2
print(multi)

suma_matriz_1 = np.array([[1, 2], [3, 4]])
suma_matriz_2 = np.array([[5, 6], [7, 8]])
suma_matriz = suma_matriz_1 + suma_matriz_2
print(suma_matriz)


[ 8 10 12]
[[ 6  8]
 [10 12]]


In [ ]:
cambio_de_forma_dimenciones = np.array([1, 2, 3, 4, 5, 6])
cambio_de_forma_matriz = cambio_de_forma_dimenciones.reshape(2, 3)
print(cambio_de_forma_matriz)

sumar_todo = np.array([[1, 2, 3], [4, 5, 6]])
suma_todo = np.sum(sumar_todo)
print(suma_todo)

[[1 2 3]
 [4 5 6]]
21


In [ ]:
calcular_la_media = np.array([[1, 2, 3], [4, 5, 6]])
media = np.mean(calcular_la_media)
print(media)

valor_minimo_y_maximo = np.array([[1, 2, 3], [4, 5, 6]])
minimo = np.min(valor_minimo_y_maximo)
maximo = np.max(valor_minimo_y_maximo)

print(minimo)
print(maximo)

3.5
1
6


In [ ]:
devuelve_el_indice = np.array([5, 2, 8, 1, 7])
indice_minimo = devuelve_el_indice.argmin()
indice_maximo = devuelve_el_indice.argmax()

print(indice_minimo)
print(indice_maximo)

calcular_desviacion_estandar = np.array([1, 2, 3, 4, 5])
desviacion_estandar = np.std(calcular_desviacion_estandar)
print(desviacion_estandar)

3
2
1.4142135623730951


In [14]:
#Ejercicios Numpy
#Creación de Arrays:
#a. Crea un array unidimensional de longitud 5 con números enteros aleatorios.
import numpy as np

unidemencional = np.random.randint(1, 10, size=5)
print(unidemencional)

#b. Crea un array bidimensional de tamaño 3x3 con valores booleanos True
bidimensional = np.full((3, 3), True)
print(bidimensional)

#c. Crea un array tridimensional de tamaño 2x3x4 con valores otantes aleatorios.
tridimencional = np.random.rand(2, 3, 4)
print(tridimencional)

#Acceso y Modicación de Elementos:
#a. Accede al tercer elemento del array creado en el ejercicio 1a.
print(unidemencional[2])

#b. Modifica el segundo elemento del array creado en el ejercicio 1b
bidimensional[1, 1] = False
print(bidimensional)

#c. Calcula la media de los elementos en la tercera dimensión del array creado en el ejercicio 1c.
media = np.mean(tridimencional)
print(media)

#Operaciones Aritméticas:
#a. Crea dos arrays unidimensionales de la misma longitud con números enteros aleatorios y realiza una suma elemento por elemento.
unidemencional1 = np.random.randint(1, 10, size=5)
unidemencional2 = np.random.randint(1, 10, size=5)
suma = unidemencional1 + unidemencional2
print(suma)

#b. Crea dos arrays bidimensionales de la misma forma y realiza una multiplicación matriz-vector
bimencional_1 = np.full(3, 3)
bimencional_2 = np.full(3, 3)
multiplicacion = bimencional_1 * bimencional_2
print(multiplicacion)

#c. Calcula el producto punto entre dos arrays tridimensionales de la misma forma
tridimencional_1 = np.random.rand(2, 3, 4)
tridimencional_2 = np.random.rand(2, 3, 4)
producto_punto = tridimencional_1 * tridimencional_2
print(producto_punto)

#Funciones y Métodos:
#a. Crea un array unidimensional con números enteros aleatorios y encuentra el valor

unidemencional = np.random.randint(1, 10, size=5)
encuentra_el_valor = np.min(unidemencional)
print(encuentra_el_valor)

#b. Crea un array bidimensional de tamaño 3x3 con valores aleatorios y calcula la suma de cada columna

#se crea un array bidimensional de tamaño 3x3 con valores aleatorios
array = np.random.randint(0, 10, size=(3, 3))

# Imprimir el array
print("Array 3x3:")
print(array)

# Calcular la suma de cada columna
suma_columnas = np.sum(array, axis=0)

# Imprimir la suma de cada columna
print("Suma de cada columna:")
print(suma_columnas)

#c. Utiliza la función np.linspace() para crear un array unidimensional con 10 elementos equidistantes entre 0 y 1.

# Crear un array unidimensional con 10 elementos equidistantes entre 0 y 1
array_unidimensional = np.linspace(0, 1, 10)

# Imprimir el array
print("Array con 10 elementos equidistantes entre 0 y 1:")
print(array_unidimensional)

#Indexación y Slicing:
#a. Crea un array unidimensional con números enteros del 0 al 9 y obtén los elementos pares

# Crear un array unidimensional con números enteros del 0 al 9
array_unidimensional_numeros_enteros_0_9 = np.arange(9)

# Obtener los elementos pares
elementos_pares = array_unidimensional_numeros_enteros_0_9[array_unidimensional_numeros_enteros_0_9 % 2 == 0]

# Imprimir el array original y los elementos pares
print("Array original:")
print(array_unidimensional_numeros_enteros_0_9)

print("Elementos pares:")
print(elementos_pares)

#b. Crea un array bidimensional de tamaño 4x4 y obtén la submatriz formada por las primeras 2 filas y las últimas 2 columnas

array_unidimensional_4x4 = np.array ([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
submatriz = array_unidimensional_4x4[:2, 2:]

print("Array Original")
print(array_unidimensional_4x4)
print("Submatriz formada por las primeras 2 filas y las últimas 2 columnas")
print(submatriz)

#c. Crea un array tridimensional de tamaño 3x3x3 y obtén el subarray formado por las primeras dos dimensiones

array_tridimensional_3x3x3 = np.arange(27).reshape(3, 3, 3)
subarray = array_tridimensional_3x3x3[:2, :, :]

print("Array Original 3x3x3")
print(array_tridimensional_3x3x3)
print("Subarray formado por las primeras dos dimensiones")
print(subarray)

[5 7 8 4 4]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[[0.52973077 0.42306534 0.38589138 0.46680716]
  [0.58393702 0.48530422 0.69079635 0.32446977]
  [0.13733572 0.55023376 0.34215667 0.80671471]]

 [[0.03923686 0.24107455 0.99439401 0.0950591 ]
  [0.93631081 0.53161174 0.65053338 0.07499955]
  [0.84683179 0.73374541 0.19649385 0.98371006]]]
8
[[ True  True  True]
 [ True False  True]
 [ True  True  True]]
0.5021018323784063
[14 11  6  8 13]
[9 9 9]
[[[0.11611413 0.24996415 0.04420371 0.20392628]
  [0.12424523 0.86014579 0.12215509 0.24541149]
  [0.20278246 0.34818128 0.12161639 0.0189466 ]]

 [[0.4134213  0.04662638 0.19375668 0.06333437]
  [0.22833609 0.2925404  0.07379697 0.51906754]
  [0.00809065 0.30911234 0.10399443 0.64973542]]]
1
Array 3x3:
[[6 1 8]
 [1 1 3]
 [9 1 9]]
Suma de cada columna:
[16  3 20]
Array con 10 elementos equidistantes entre 0 y 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.   